:global:
  componentName: cert-manager
  githubUrl: https://github.com/projectsyn/component-cert-manager
  feature_goUnitTests: false
  feature_goldenTests: true

docs/antora.yml:
  name: cert-manager
  title: cert-manager
