= Parameters

The parent key for all of the following parameters is `cert_manager`.


== `namespace`

[horizontal]
type:: string
default:: `syn-cert-manager`

The namespace in which to install cert-manager.

The component always adds label `openshift.io/cluster-monitoring=true` to the namespace.
Additionally, if component `prometheus` is installed on the cluster, the component registers the namespace to be monitored through the default Prometheus stack managed by that component.


== `charts`

[horizontal]
type:: object
default::
+
[source,yaml]
----
charts:
  cert_manager:
    source: https://charts.jetstack.io
    version: v1.16.2
----

Specifies the Helm charts sources and versions for certificate-related components.


== `images`

[horizontal]
type:: object
default::
+
[source,yaml]
----
images:
  cert_manager:
    registry: quay.io
    repository: jetstack/cert-manager-controller
  cert_webhook:
    registry: quay.io
    repository: jetstack/cert-manager-webhook
  cert_cainjector:
    registry: quay.io
    repository: jetstack/cert-manager-cainjector
  cert_acmesolver:
    registry: quay.io
    repository: jetstack/cert-manager-acmesolver
  cert_startupapi:
    registry: quay.io
    repository: jetstack/cert-manager-startupapicheck
  kubectl:
    registry: quay.io
    repository: appuio/oc
    tag: 'v4.16'
----

Image registry configurations for components.


== `component`

Configuration options for certificate-related components.

=== `component.cert_manager`

[horizontal]
type:: object
default::
+
[source,yaml]
----
component:
  cert_manager:
    httpProxy: '' <1>
    httpsProxy: ''
    noProxy: ''
    certificateOwnerRef: false <2>
    recursiveNameservers: '1.1.1.1:53' <3>
    recursiveNameserversOnly: true <4>
----
<1> Proxy configuration for isolated environments.
<2> Ensures secrets will be automatically removed when the certificate resource is deleted.
<3> Recursive nameservers to use for validating DNS01 challenges.
<4> Ensures that only the configured nameservers are used to validate DNS01 challenges.

Configuration options for cert-manager.

See the https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check[cert-manager documentation] for nameserver config.


== `acmeClients`

[horizontal]
type:: object
default:: `{}`

Configuration for ACME DNS clients.

For a detailed explanation of how the self-registration works, see the xref:explanations/acme-dns-self-registration.adoc[acme-dns self-registration] documentation.

[NOTE]
====
The entries in `fqdns` must be exact matches the FQDNs for which DNS01 challenges should be presented.
The only flexibility is that cert-manager will present a DNS01 challenge for the wildcard FQDN `*.example.com`, if `example.com` is listed in `fqdns`.
====

=== Example

[source,yaml]
----
acmeClients:
  vshn-default: <1>
    api:
      endpoint: https://acme-dns-api.example.com
      username: vshn-default-username
      password: vshn-default-password
    fqdns:
      - 'api.${cluster:name}.example.com'
      - '*.apps.${cluster:name}.example.com'
----
<1> Name of the ACME client, referenced in `clusterIssuers.acmeClientRefs`.


== `solvers`

[horizontal]
type:: object
default::
+
[source,yaml]
----
solvers:
  nginx_http01:
    http01:
      ingress:
        class: 'nginx'
----

Configuration for acme solvers.

See https://cert-manager.io/docs/configuration/acme/#configuration for configurable parameters.

=== Example

[source,yaml]
----
solvers:
  openshift_http01: <1>
    http01:
      ingress:
        class: null
        ingressTemplate:
          metadata:
            annotations:
              route.openshift.io/termination: edge
----
<1> Name of the solver, referenced in `clusterIssuers.solverRefs`.


== `clusterIssuers`

[horizontal]
type:: object
default::
+
[source,yaml]
----
clusterIssuers:
  letsencrypt-staging:
    solverRefs:
      - nginx_http01
  letsencrypt-production:
    solverRefs:
      - nginx_http01
----

Configuration for cluster-wide certificate issuers.

See the https://cert-manager.io/docs/concepts/issuer/[cert-manager documentation] for how to configure such issuers.

=== Example

[source,yaml]
----
clusterIssuers:
  letsencrypt-production:
    solverRefs:
      - nginx_http01
    acmeClientRefs:
      - vshn-default
  other-issuer:
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
          - http01:
              ingressClass: nginx
----


== `issuers`

[horizontal]
type:: object
default:: `{}`

Configuration for certificate issuers.

See the https://cert-manager.io/docs/concepts/issuer/[cert-manager documentation] for how to configure such issuers.

=== Example

[source,yaml]
----
issuers:
  namespace-a/ca-issuer:
    spec:
      ca:
        secretName: ca-key-pair
  ca-issuer:
    metadata:
      namespace: namespace-b
    spec:
      ca:
        secretName: ca-key-pair
----


== `secrets`

[horizontal]
type:: dictionary
default:: `{}`

A dictionary holding secrets, eg. for DNS01 solvers.

See the https://cert-manager.io/docs/configuration/acme/dns01/[cert-manager documentation] for DNS01 solvers which are supported by cert-manager.


== `resources`

[horizontal]
type:: object
default::
+
[source,yaml]
----
resources:
  cert_manager:
    requests:
      cpu: 50m
      memory: 512Mi
  cert_webhook:
    requests:
      cpu: 50m
      memory: 64Mi
  cert_cainjector:
    requests:
      cpu: 50m
      memory: 512Mi
----

Resource requests and limits for the components containers.


== `helmValues`

[horizontal]
type:: object
default::
+
[source,yaml]
----
helmValues:
  cert_manager: {}
----

Override configurations for individual components.
