= Parameters

The parent key for all of the following parameters is `cert_manager`.


== `namespace`

[horizontal]
type:: string
default:: `syn-cert-manager`

The namespace in which to install cert-manager.

The component always adds label `openshift.io/cluster-monitoring=true` to the namespace.


== `charts`

[horizontal]
type:: object
default::
+
[source,yaml]
----
charts:
  cert_manager:
    source: https://charts.jetstack.io
    version: v1.16.2
----

Specifies the Helm charts sources and versions for certificate-related components.


== `images`

[horizontal]
type:: object
default::
+
[source,yaml]
----
images:
  cert_manager:
    registry: quay.io
    repository: jetstack/cert-manager-controller
  cert_webhook:
    registry: quay.io
    repository: jetstack/cert-manager-webhook
  cert_cainjector:
    registry: quay.io
    repository: jetstack/cert-manager-cainjector
  cert_acmesolver:
    registry: quay.io
    repository: jetstack/cert-manager-acmesolver
  cert_startupapi:
    registry: quay.io
    repository: jetstack/cert-manager-startupapicheck
  kubectl:
    registry: quay.io
    repository: appuio/oc
    tag: 'v4.16'
----

Image registry configurations for components.


== `config`

Configuration options for certificate-related components.

=== `config.common`

[horizontal]
type:: object
default::
+
[source,yaml]
----
config:
  common:
    httpProxy: ''
    httpsProxy: ''
    noProxy: ''
    email: ''
----

Common configuration options for certificate-related components.

=== `config.cert_manager`

[horizontal]
type:: object
default::
+
[source,yaml]
----
config:
  cert_manager:
    certificateOwnerRef: false
    recursiveNameservers: '1.1.1.1:53'
    recursiveNameserversOnly: true
----

Configuration options for cert-manager.


== `letsencrypt_email`

[horizontal]
type:: string
default:: ``

The email address Let's Encrypt will use to contact you.

== `dns01-recursive-nameservers`

[horizontal]
type:: string
default:: `1.1.1.1:53`

Recursive nameservers to use for validating DNS01 challenges.
See the https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check[cert-manager documentation] for more details.

This parameter is injected into parameter `helm_values` as an extra argument to cert-manager (`helm_values.extraArgs`).

[NOTE]
====
We additionally also set `--dns01-recursive-nameservers-only` as an argument to cert-manager.
This ensures that only the nameservers configured in this parameter are used to validate DNS01 challenges.
====

== `http_proxy`

[horizontal]
type:: string
default:: ``

The value of `http_proxy` is passed to cert-manager in environment variable `HTTP_PROXY`.

This parameter is injected into parameter `helm_values` in field `extraEnv`.

== `https_proxy`

[horizontal]
type:: string
default:: ``

The value of `https_proxy` is passed to cert-manager in environment variable `HTTPS_PROXY`.

This parameter is injected into parameter `helm_values` in field `extraEnv`.

== `no_proxy`

[horizontal]
type:: string
default:: ``

The value of `no_proxy` is passed to cert-manager in environment variable `NO_PROXY`.

This parameter is injected into parameter `helm_values` in field `extraEnv`.

== letsencrypt_clusterissuers

[horizontal]
type:: dictionary
default::
+
[source,yaml]
----
staging: true
production: true
----

This parameter allows users to control which Let's Encrypt cluster issuers are generated by the component.
Generally, we recommend deploying both the staging and production cluster issuers.

However, in certain cases it may make sense to not deploy the Let's Encrypt cluster issuers.
If you disable both Let's Encrypt cluster issuers, you'll have to setup suitable issuers or cluster issuers manually in order to make use of cert-manager.

== `solvers`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the solvers for the default cluster issuers.

See https://cert-manager.io/docs/configuration/acme/#configuration for configurable parameters.

== `secrets`

[horizontal]
type:: dictionary
default:: `{}`

A dictionary holding secrets for DNS01 solvers.
Each key in the dictionary is used as the name of a secret.
The value of the key is merged directly into an empty Kubernetes `Secret` resource.
By default, secrets are created in the namespace in which cert-manager is deployed.

See the https://cert-manager.io/docs/configuration/acme/dns01/[cert-manager documentation] for DNS01 solvers which are supported by cert-manager.

== `cluster_issuers`, `issuers`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
issuers:
  ca-issuer:
    metadata:
      namespace: mesh-system
    spec:
      ca:
        secretName: ca-key-pair

cluster_issuers:
  ca-issuer:
    spec:
      ca:
        secretName: ca-key-pair
----

Dictionaries holding issuers and cluster issuers.
Each key in the dictionary is used as the name of an issuer.
The value of the key is merged directly into an empty Kubernetes `(Cluster)Issuer` resource.

See the https://cert-manager.io/docs/concepts/issuer/[cert-manager documentation] for how to configure such issuers.

== `acme_dns_api`

[horizontal]
type:: dictionary
keys:: `endpoint`, `username`, `password`, `fqdns`
default:: `{}`

The component sets up a Job and Cronjob to register and check acme-dns client credentials if key `endpoint` is present and non-null in this parameter.
If key `endpoint` is missing or `null` the component doesn't configure the acme-dns client registration.

For a detailed explanation of how the self-registration works, see the xref:explanations/acme-dns-self-registration.adoc[acme-dns self-registration] documentation.

If key `endpoint` is present and non-null, the component expects that the other keys listed above are also present. The keys have the following meaning:

`endpoint`:: The HTTP API endpoint of the acme-dns instance
`username`:: The HTTP basic authorization username for the acme-dns instance `/register` endpoint
`password`:: The HTTP basic authorization password for the acme-dns instance `/register` endpoint.
We strongly recommend specifying the password as a Vault secret reference.
`fqdns`:: A list of FQDNs for which the acme-dns instance can be used to solve DNS01 challenges.
This list must contain at least one entry.

TIP: See xref:how-tos/dns01.acme[Using DNS01 challenges] for instructions to setup and use the acme-dns self-registration mechanism.

[NOTE]
====
The entries in `fqdns` must be exact matches the FQDNs for which DNS01 challenges should be presented.
The only flexibility is that cert-manager will present a DNS01 challenge for the wildcard FQDN `*.example.com`, if `example.com` is listed in `fqdns`.
====


== `resources`

[horizontal]
type:: object
default::
+
[source,yaml]
----
resources:
  cert_manager:
    requests:
      cpu: 50m
      memory: 512Mi
  cert_webhook:
    requests:
      cpu: 50m
      memory: 64Mi
  cert_cainjector:
    requests:
      cpu: 50m
      memory: 512Mi
----

Resource requests and limits for the components containers.


== `overrides`

[horizontal]
type:: object
default::
+
[source,yaml]
----
overrides: {}
----

Override configurations for individual components.
