= Parameters

The parent key for all of the following parameters is `cert_manager`.

== `namespace`

[horizontal]
type:: string
default:: `syn-cert-manager`

The namespace in which to install cert-manager.

== `charts:cert-manager`

[horizontal]
type:: string
default:: `v0.15.1`

The version of the Helm chart to use.

== `letsencrypt_email`

[horizontal]
type:: string
default:: ``

The email address Let's Encrypt will use to contact you.

== `dns01-recursive-nameservers`

[horizontal]
type:: string
default:: `1.1.1.1:53`

Recursive nameservers to use for validating DNS01 challenges.
See the https://cert-manager.io/docs/configuration/acme/dns01/#setting-nameservers-for-dns01-self-check[cert-manager documentation] for more details.

== `http_proxy`

[horizontal]
type:: string
default:: ``

The value of `http_proxy` is passed to cert-manager in environment variable `HTTP_PROXY`.


== `https_proxy`

[horizontal]
type:: string
default:: ``

The value of `https_proxy` is passed to cert-manager in environment variable `HTTPS_PROXY`.

== `no_proxy`

[horizontal]
type:: string
default:: ``

The value of `no_proxy` is passed to cert-manager in environment variable `NO_PROXY`.

== `solvers`

[horizontal]
type:: dictionary
default:: see `defaults.yml`

A dictionary holding the solvers for the default cluster issuers.

See https://cert-manager.io/docs/configuration/acme/#configuration for configurable parameters.

== `secrets`

[horizontal]
type:: dictionary
default:: `{}`

A dictionary holding secrets for DNS01 solvers.
Each key in the dictionary is used as the name of a secret.
The value of the key is merged directly into an empty Kubernetes `Secret` resource.
By default, secrets are created in the namespace in which cert-manager is deployed.

See the https://cert-manager.io/docs/configuration/acme/dns01/[cert-manager documentation] for DNS01 solvers which are supported by cert-manager.

== `acme_dns_api`

[horizontal]
type:: dictionary
keys:: `endpoint`, `username`, `password`, `domains`
default:: `{}`

The component sets up a Job and Cronjob to register and check acme-dns client credentials if key `endpoint` is present in this parameter.
For a detailed explanation of how the self-registration works, see the xref:explanations/acme-dns-self-registration.adoc[acme-dns self-registraion] documentation.

If key `endpoint` is present, the component expects that the other keys listed above are also present. The keys have the following meaning:

`endpoint`:: The HTTP API endpoint of the acme-dns instance
`username`:: The HTTP basic authorization username for the acme-dns instance `/register` endpoint
`password`:: The HTTP basic authorization password for the acme-dns instance `/register` endpoint.
We strongly recommend specifying the password as a Vault secret reference.
`domains`:: A list of domains for which the acme-dns instance can be used to solve DNS01 challenges.
This list must contain at least one entry.

TIP: See xref:how-tos/dns01.acme[Using DNS01 challenges] for instructions to setup and use the acme-dns self-registration mechanism.

== Example

[source,yaml]
----
solvers:
  nginx_http01:
    http01:
      ingress:
        podTemplate:
          metadata:
            labels:
              app: "solver"
  dns01:
    acmeDNS:
      accountSecretRef:
        name: acmedns
          key: acmedns.json
        host: auth.example.com

secrets:
  acmedns:
    stringData:
      acmedns.json: ?{vaultkv:${cluster:tenant}/${cluster:name}/acmedns}
----
